# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True)),
                ('review', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='stall',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsec.Stall'),
        ),
    ]
