# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsec', '0002_auto_20180429_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('stall_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stall',
        ),
        migrations.AddField(
            model_name='review',
            name='stall_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
