# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsec', '0003_auto_20180429_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stall_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stall_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
