# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsec', '0004_auto_20180429_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
