# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsec', '0006_rating_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='photourl',
            field=models.URLField(blank=True, default=''),
        ),
    ]
